name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.0
    - name: Cache
      uses: actions/cache@v2
      with:
        path: DerivedData
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      with:
        # The lane that should be executed.
        lane: test
